name: Deployment Pipeline
#events

on:
# event 1
  push:
    branches: [ "main" ]
# event 2    
# pull_request:
#    branches: [ "main" ]

jobs:
  deploy:

    runs-on: ubuntu-latest

#  strategy:
#      matrix:
#       node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: "Build Docker Image"
      run: docker build -t rosey.jadon/sample-node-app .
    - name: "Build Successful!!!!"
      run: echo "Docker Image Built Successfully!"
    - name: "Login with Docker Credentials"
      run: echo "dckr_pat_Ge1DuiW7tEinq7ryB06RcOgctbI" | docker login -u "rosey.jadon" password-stdin
    - name: "Login Successful"
      run: echo "Logged in to Docker Hub Successfully!"
      
    
    

  